import { tool } from "@anthropic-ai/claude-agent-sdk";
import { z } from "zod";
import fs from "fs/promises";
import path from "path";
import { DATA_DIR, toolResponse } from "./shared.js";

export const composeLessonPlanTool = tool(
  "compose_lesson_plan",
  "Compose a structured lesson plan from skill graph, learner profiles, and constraints. Writes the plan to data/lessons/ and returns the content.",
  {
    title: z.string().describe("Lesson plan title"),
    domain: z.string().describe("Skill domain"),
    groupName: z.string().describe("Group slug"),
    topic: z.string().describe("Main topic of the lesson"),
    duration: z.string().describe("e.g. '90 minutes'"),
    setting: z.string().optional().describe("e.g. 'computer lab', 'classroom'"),
    educatorName: z.string().optional().describe("Educator's name"),
    objectives: z
      .array(z.string())
      .describe("Learning objectives for the session"),
    targetSkills: z
      .array(z.string())
      .describe("Skills this lesson aims to teach"),
    constraints: z
      .string()
      .optional()
      .describe("Any constraints (tools, connectivity, etc.)"),
    planContent: z
      .string()
      .describe(
        "The full Markdown content of the lesson plan, generated by the agent using the compose-lesson skill and template"
      ),
  },
  async ({
    title,
    domain,
    groupName,
    topic,
    duration,
    setting,
    educatorName,
    objectives,
    targetSkills,
    constraints,
    planContent,
  }) => {
    const lessonsDir = path.join(DATA_DIR, "lessons");
    await fs.mkdir(lessonsDir, { recursive: true });

    const now = new Date();
    const dateSlug = now.toISOString().slice(0, 10);
    const slug = title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "");
    const filename = `${dateSlug}-${slug}.md`;
    const filePath = path.join(lessonsDir, filename);

    await fs.writeFile(filePath, planContent, "utf-8");

    return toolResponse({
      title,
      file: filePath,
      filename,
      domain,
      group: groupName,
      topic,
      duration,
      setting: setting ?? "not specified",
      educator: educatorName ?? "not specified",
      objectives,
      targetSkills,
      constraints: constraints ?? "none",
      created: now.toISOString(),
      planContent,
    });
  }
);
